let sachin={
    color:"black",
    height: "6 fit",
    shoes:"sparx",
    tshirt:"levis",
    pent:"Metronout",
    marks:[52 , 71, 73 ,90, 91, 59],
}

let gaurav={
    color:"white",
    height: "3 fit",
    shoes:"nike",
    tshirt:"yellow",
    pent:"formal",
    marks:[50 , 78, 79 ,90, 96, 57],
    say (){
        console.log(sachin.pent +" tfgycyCXHSGADFG "+ this.pent);
        
    }

}
gaurav.say();



