// var data = [
//   {
//     que: "what is the population ? ",
//     options: [
//       { label: "12000", value: 12000 },
//       { label: "15k", value: 15000 },
//       { label: "20k", value: 20000 },
//     ],
//   },
// ];
// ///////1st
// var a = data[0];
// var s1 = a.options[0];
// console.log(s1);


// Function in foreach
// let arr=[10, 20, 30, 40, 50 ,60, 70 ,80, 90];
// arr.forEach(all=>{
//     console.log(all);
// });


// include or not
// const arr=[10, 20, 30, 40, 50 ,60, 70 ,80, 90];
// var a=arr.includes(50);
// console.log(a);


// array Filter

// const arr=[10, 20, 30, 40, 50 ,60, 70 ,80, 90];
// let filter=arr.filter(num=>num>30);
// console.log(filter);

//  array map
// const arr=[10, 20, 30, 40, 50 ,60, 70 ,80, 90];
// let map=arr.map(num=>num+5);
// console.log(map);


//
const arr=[10, 20, 30, 40, 50 ,60, 70 ,80, 90];





